# Generated by Django 2.1 on 2018-08-20 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=250)),
                ('equipment_pic', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=250)),
                ('sport_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theapp.Sport'),
        ),
    ]
