# Generated by Django 2.1 on 2018-08-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0002_auto_20180822_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='age',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='gender',
        ),
        migrations.AddField(
            model_name='equipment',
            name='desc',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='equipment',
            name='price',
            field=models.FloatField(default=None),
        ),
    ]
