# Generated by Django 2.1 on 2018-08-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0005_mycart_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='items',
            field=models.ManyToManyField(to='theapp.UserProfile'),
        ),
    ]
